### PR TITLE
changes for diagrams-input

### PR DESCRIPTION
**Pull request by tkvogt**

### CODE REVIEW

**Comment by cchalmers** [comment]
I'm unclear on the motivation behind this. Could you change your `loadImageEmb` and `loadImageExt` in `diagrams-input` to

```
loadImageEnb :: (TypeableFloat n, Renderable (Path V2 n) b, Renderable (DImage n Embedded) b)
  => FilePath -> IO (Either String (QDiagram b V2 n Any))
```

```
loadImageExt :: TypeableFloat n, Renderable (Path V2 n) b, Renderable (DImage n External) b
  => FilePath -> IO (Either String (QDiagram b V2 n Any))
```

by wrapping it in a `DImage` if it's an image or just rendering the SVG paths to a diagram if it's an svg file? What's the advantage of putting it in an `ImageData`?

**Comment by tkvogt** [comment]
I agree that loadImageEmb and loadImageExt should return an Either String QDiagram. I also don't understand why there are two functions: One to to turn a file into a DImage (loadImageEmb and loadImageExt) and another to turn this DImage into a QDiagram (image). I thought that the person who did this had his reasons and just kept on to it.
If no one can explain to me the advantage of this two step approach to load an image I wil  change it like you propose.

**Comment by cchalmers** [comment]
Ah yeah, I see what you mean. I say we keep the current `loadImageEmb`, `loadImageExt`, I'd like to reducing breaking changes (and they could be used for 3D) and choose different names for the `diagrams-inputs` versions that go straight to diagrams.

**Comment by tkvogt** [comment]
I changed diagrams-input so that instead of integrating readSVG in loadImageEmb/loadImageExt, loadImageEmb/loadImageExt is integrated in the new loadImageEmbedded/loadImageExternal: https://github.com/diagrams/diagrams-input/blob/91f88b58564b6b4bc79865fa052de0938d821621/src/Diagrams/TwoD/Input.hs#L46

Now this pull request is not necessary anymore. But before changing the manual, should  diagrams-input be added to the build process when entering "cabal install diagrams"?

**Comment by byorgey** [comment]
@tkvogt Yes, my idea was indeed to add `diagrams-input` to the `diagrams` package, if we all agree that's what we want to do.

**Pull request closed without merging**
