### PR TITLE
Projections

### PR DESCRIPTION
**Pull request by cchalmers**
Not ready.

Just a start at projections of path-like things. I'm still working things out and open to suggestions.

- [x] Added `LinearMappable` class
- [x] Added `AffineMappable` class
- [x] Added Matrix functions
- [x] Add common orthographic projection functions
- [ ] Add projections from `Camera`s
- [x] Perspective projections using `Deformable`

### CODE REVIEW

**Comment by cchalmers** [comment]
Sorry it took so long to make the small fixes, I'll merge this too after travis builds.

**Comment by bergey** [comment]
Great.  I was worried that the ball was in my court, and I'd forgotten.

**Comment by cchalmers** [comment]
Nah, I was just busy on doc and forgot about it. Speaking of which there's diagrams/diagrams-doc#79 if you're looking for something to do :)

If not I'll get back to it eventually. I just got a little bored and needed a break from it.

**Comment by bergey** [comment]
I won't get to it this weekend, but likely later this week.

**Comment by cchalmers** [comment]
Great, thanks.

**Pull request merged**
