### PR TITLE
new attributes for separate fill & stroke opacity

### PR DESCRIPTION
**Pull request by byorgey**
See #248.

Questions I'd like help thinking about: (1) what should be the semantics of the combination of opacity, fill-opacity, and stroke-opacity attributes?  (2) what is the right way to upgrade backends to support these attributes?

### CODE REVIEW

**Comment by byorgey** [comment]
Travis is failing because of the thing with `lens` no longer exporting `coerce`.  We need to figure out what to do about that...

**Comment by tkvogt** [comment]
I see it like this:
(1) semantics of combining opacities: opacities of one sort have to be multiplied: e.g. # fill-opacity 0.8 # fill-opacity 0.8 = # fill-opacity 0.64 .
(2) In the svg backend the 3 sorts of opacities are orthogonal, and don't have to be combined, just added.
Other backends that don't know fill or stroke opacity have to draw two diagrams. stroke-opacity has to be multiplied with opacity for the first diagram and fill-opacity also has to be multiplied with opacity for the second.

**Comment by bergey** [comment]
https://github.com/diagrams/diagrams-lib/commit/db1f5c9cc52bfff88c74a7b54fc084552a814cee fixes the travis build re `coerce`.  It's hacky, and I'm fine with some other solution, but this seemed least disruptive in the short run.

**Comment by byorgey** [comment]
@cchalmers suggested simply not hiding `coerce`, which I like except for the fact that technically that requires a minor version bump, since we are now exporting something extra: the code of anyone using diagrams + an older version of `lens` + `coerce` would break.  On the other hand, the number of people in that situation is likely to be approximately zero.

**Comment by byorgey** [comment]
@tkvogt but what if you set, say, both the `opacity` and the `fill-opacity`?  What should be the semantics then?  Should it just ignore the `opacity`?  Multiply them together? etc.?

**Comment by bergey** [comment]
That minor version bump is the reason I didn't take the *unhide* approach unilaterally.  I just wanted the travis build to green-light.  But I'm fine with that solution.

**Comment by tkvogt** [comment]
@byorgey The SVG spec says that "object/group opacity can be thought of conceptually as a postprocessing operation" (http://www.w3.org/TR/SVG/masking.html#OpacityProperty)
So `stroke-opacity` and `fill-opacity` are multiplied with `opacity`. If `stroke-opacity`, `fill-opacity` or `opacity` is not set then it has standard value 1. After having read the svg spec quite a lot I consider it quite a good guideline.

**Comment by byorgey** [comment]
@tkvogt Thanks, that makes sense.  Mostly I was trying to figure out whether e.g. setting `stroke-opacity` or `fill-opacity` should set the `opacity` automatically as well, but it sounds like the answer is no, they are all independent attributes and one might reasonably want to use all three of them together.

**Comment by byorgey** [comment]
In that case I think this is ready to merge.  Updating the SVG backend to use these should be easy.  Updating other backends to support them sounds much harder.

**Pull request merged**
