### PR TITLE
Attempt to fix some issues with Bezier intersections.

### LINKED ISSUE #322: section producing incorrect results
Both red sections have the same start parameters and should therefore start in the same place.
```haskell
{-# LANGUAGE FlexibleContexts #-}
{-# LANGUAGE TypeFamilies #-}
import Diagrams.Prelude
import Diagrams.Backend.Cairo.CmdLine

ex :: Diagram Cairo
ex = (sec 0 (0.5) <> sec (0.5) 1     # lc red) # pad 1.1
 ||| (sec 0 (0.5) <> sec (0.5) (0.8) # lc red) # pad 1.1
  where
    sec a b = strokeP $ toPath (section (circle 1) a b :: Located (Trail V2 Double))

main = mainWith ex
```

### LINKED ISSUE #323: segmentSegment can fail to terminate on very specific and seemingly innocuous inputs
Slight perturbations of d and r avoid the bug, as does increasing e (default 1e-8).  
```haskell
{-# LANGUAGE FlexibleContexts #-}
{-# LANGUAGE TypeFamilies #-}
import Diagrams.Prelude
import Diagrams.TwoD.Segment

d = 72       -- ~ 71.9 to 72.1
r = d/64     -- ~ 64 to 64.0000001
e = 6.969e-8 -- ~ <= 6.969e-8

path :: Path V2 Double
path = circle r # translateY d

trails :: [Located (Trail V2 Double)]
trails = head $ explodePath path

(s0:s1:_) = map (head . fixTrail) trails

bad = segmentSegment e s0 s1

-- Does not terminate or produce output.
main = print bad
```

### PR DESCRIPTION
**Pull request by fryguybob**
There are several issues with the code for Bezier
Bezier intersections right now.  This tries to fix
some of them.  I haven't been able to test yet due
to my ghc/cabal being ... interesting.

Hopefully this fixes #323.

### CODE REVIEW

**Comment by byorgey** [comment]
I think you mean it fixes #323 (wrong results from `segmentSegment`) , not #322 (wrong results from `section`), right?

**Comment by fryguybob** [comment]
Woops!  Yes fixes #323.  Now how to fix this...

**Comment by byorgey** [comment]
Probably the easiest is to just close this PR and open a new one with a corrected comment, so it doesn't close the wrong issue when we eventually merge it.

**Comment by byorgey** [comment]
Oh, never mind, I see you were able to just edit the comment.

**Comment by fryguybob** [comment]
It is still attached to the wrong issue though.  I'll just close and re-request.

**Pull request closed without merging**
