### PR TITLE
Backport of PR #264 to release branch

### LINKED ISSUE #263: Broken offset joins with non-vertices in loops
I get broken offset paths when drawing a rectangle that has more points than just the four corners.

This happens with diagrams 1.3.0.3, it used to work with diagrams 1.2.

```
dia :: Diagram B
dia = (stroke p # lc blue)
    <> (stroke (offsetPath (-0.1 :: Double) p) # lc red)
    <> (stroke (offsetPath (0.1  :: Double) p) # lc green)
  where
    p :: Path V2 Double
    p = pathFromTrail . wrapTrail . glueLine . lineFromVertices . map p2 $
--          [(0,0), (2,0), (2,1), (2,2), (0,2), (0,0)] -- broken
            [(0,0), (2,0), (2,2), (0,2), (0,0)] -- fine
```

broken
fine

### PR DESCRIPTION
**Pull request by robx**
As per discussion in #264. Fixes #263. Includes @fryguybob's follow-up commit.

diagrams-lib's test target passes, and everything looks as it should in my puzzle rendering. Is there some other test suite to run?

### CODE REVIEW

**Comment by bergey** [comment]
Thanks!  I'll merge & upload today after the CI build completes.

That's enough testing for me.  We don't have nearly as many tests as I'd like, and they're scattered about inconveniently.  Your PR improves the state of affairs.  If you're curious, there are some tests in:

https://github.com/diagrams/diagrams-test
https://github.com/diagrams/diagrams-backend-tests

**Comment by bergey** [comment]
Hmm.  `release` has been failing CI for a while, and now it's failing because linear is out of sync with transformers / transformers-compat.  So I'll merge anyway.

**Comment by robx** [comment]
Thanks!

**Comment by bergey** [comment]
uploaded as `1.3.1.0`

**Pull request merged**
