### PR TITLE
Queries

### PR DESCRIPTION
**Pull request by cchalmers**
See also diagrams/diagrams-core#88.
Should be ready do merge.

Generalises @bergey's `Inside` classes. I've called it `HasQuery` with a `getQuery` method to be more consistent with other similar classes. It also has an `m` parameter for to support extra queries. Most are just `Any`, `Diagram` and `Query` has `m`.

Path like things have a `Crossings` query that counts the number of crossings in the positive x direction from the query point. `isInsideWinding` and `isInsideEvenOdd` now use this so they can be used on trails and loops as well as paths. (The arguments of these functions where also flipped to be more consistent with other query-like function.)

### CODE REVIEW

**Comment by byorgey** [comment]
This all looks great to me. @bergey , any other comments?

**Comment by bergey** [comment]
LGTM.  I like `inquire` and the examples.

**Comment by byorgey** [comment]
By the way, @cchalmers , it looks like this broke `diagrams-pgf`, see http://gondor.cs.hendrix.edu:8080/job/Diagrams%20HEAD/29/console .  Could you fix that when you get a chance?

**Comment by byorgey** [comment]
Our CI server is already paying off =D

**Comment by cchalmers** [comment]
Ah yeah, sure.  :D

**Pull request merged**
