### PR TITLE
Converting B-splines to beziers

### PR DESCRIPTION
**Pull request by byorgey**
The fruits of my labor to get graphviz stuff working properly --- it turned out to not be necessary for graphviz after all, but is generally useful nonetheless.

### CODE REVIEW

**Comment by bergey** [comment]
Looks good to me.  Restricting it to uniform splines really does make the code much easier to read.  

The Sederberg has been on my reading list for a long time; I wish I'd read it sooner.  (Actually, [these course notes](http://tom.cs.byu.edu/~557/text/cagd.pdf) chapter 6 of which seems to be a somewhat expanded version of the 2005 version.)  I hadn't realized the Ramshaw was online.

**Comment by bergey** [comment]
Travis is failing on HP-2013 due to a change in lens.  I [reported it upstream.](https://github.com/ekmett/lens/issues/564)

**Comment by byorgey** [comment]
It's not quite as general as it could be since it insists on duplicating the knots at the end.  But I judged that would make for the nicest default behavior.  If anyone yells we can easily add a variant that doesn't do any duplicating.

**Comment by byorgey** [comment]
I think this is ready to merge now, along with https://github.com/diagrams/diagrams-doc/pull/92 .

**Pull request merged**
